# Globals/defaults
verbose: true
debug: false
priority: 1000
path: some_string

override_test:
  verbose: false
  debug: true
  priority: 2000
  path: some_other_string

first_level_list:
  - string1
  - string2

list_test:
  list_strings:
    - string1
    - string2
    - string3

  list_ints:
    - -1
    - -2
    - 3

  list_uints:
    - 1
    - 2
    - 3

int_bounds:
  uint16_max: 65535
  gt_uint16: 65536
  int16_min: -32768
  lt_int16: -32769

map_test:
  one: 1
  two: 2
  three: 3
  four: 4
  five: 5

